### ISSUE TITLE
КОНСТАНТЫ_ОБЫЧНО_ТАКИМ_ОБРАЗОМ_ПИШУТ

### ISSUE THREAD

**Issue by denis-bosiy** [adelsibga/TL-summer#14]
https://github.com/adelsibga/TL-summer/blob/8328cd542c5399e1b7c37688af337da5902ac146/HomeTask/07/src/App.tsx#L7

**Comment by adelsibga** [comment]
[Исправил](https://github.com/adelsibga/TL-summer/commit/2726169a38ae50e476a89788a745cae8c3dfe42f)
