### ISSUE TITLE
Типов нет нигде :-(

### ISSUE THREAD

**Issue by denis-bosiy** [adelsibga/TL-summer#15]
https://github.com/adelsibga/TL-summer/blob/8328cd542c5399e1b7c37688af337da5902ac146/HomeTask/07/src/components/feedbackForm/feedbackForm.tsx#L6C45-L6C45

**Comment by adelsibga** [comment]
[Исправил](https://github.com/adelsibga/TL-summer/commit/c72efc4dc67a9857eb4c58d6c4b135589163031f)
