### ISSUE TITLE
Не прописан внешний ключ

### ISSUE THREAD

**Issue by AlekseiPavlovskii** [adelsibga/TL-summer#16]
https://github.com/adelsibga/TL-summer/blob/af3860dadb5e34c4cb8f0ced0ffe89e7f0044c51/HomeTask/03/MintCreate.sql#L15

Нет объявления внешнего ключа, де-факто таблицы не связаны

**Comment by adelsibga** [comment]
[Исправил](https://github.com/adelsibga/TL-summer/commit/f955e8533ec1fa691dd639251202e991555e6780)
