### ISSUE TITLE
Отсутствует not null

### ISSUE THREAD

**Issue by AlekseiPavlovskii** [adelsibga/TL-summer#17]
https://github.com/adelsibga/TL-summer/blob/af3860dadb5e34c4cb8f0ced0ffe89e7f0044c51/HomeTask/03/MintCreate.sql#L15

Not null есть только у первичных ключей. Нужно посмотреть, какие поля обязаны быть заполненными (например название заведения), и прописать им not null

**Comment by adelsibga** [comment]
[Исправил](https://github.com/adelsibga/TL-summer/commit/ccd34db0376691ec32e50c73e04249c500b7efc8)
