### ISSUE TITLE
Кодировка

### ISSUE THREAD

**Issue by AlekseiPavlovskii** [adelsibga/TL-summer#18]
https://github.com/adelsibga/TL-summer/blob/af3860dadb5e34c4cb8f0ced0ffe89e7f0044c51/HomeTask/03/MintInsert.sql#L162

Слетела кодировка

**Comment by adelsibga** [comment]
[Исправил](https://github.com/adelsibga/TL-summer/commit/67693ca139d3a446a3260d23eb9019ef08a29df9)
