### ISSUE TITLE
BubbleSort: Можно упростить код с помощью String.Join

### ISSUE THREAD

**Issue by LehaIvanov** [adelsibga/TL-summer#2]
Не знаю, знаком ли ты с полиморфизмом или нет (я думаю, что знаком:))), но для вывода результата в консоль можно использовать [String.Join](https://learn.microsoft.com/en-us/dotnet/api/system.string.join?view=net-7.0#system-string-join-1(system-string-system-collections-generic-ienumerable((-0)))).

**Comment by adelsibga** [comment]
Исправил
