### ISSUE TITLE
BubbleSort: Поправить именование переменных

### ISSUE THREAD

**Issue by LehaIvanov** [adelsibga/TL-summer#3]
Мне не нравится названия пременных `arr` и `tmp`.  Вообще вопрос спорный, некоторые сокращения допустимы. Из `arr` и `tmp` я сразу понял, что ты имеешь в виду, но всё таки лучше сокращения не использовать, если можно. В данном случае сильно больше кода не станет, если ты назовёшь переменную `temp`.

А переменная `arr` раскрывает свой тип, не очень хорошо так делать, вдруг тип переменной в процессе разработки поменяется на `IList`, `IEnumerable`, ... Лучше давать более семантические названия, в данном случае `numbers`, `elements`, `items` на мой взгляд лучше.

**Comment by adelsibga** [comment]
Исправил
