### ISSUE TITLE
BubbleSort: Можно упростить алгоритм - уменьшить количество итераций

### ISSUE THREAD

**Issue by LehaIvanov** [adelsibga/TL-summer#4]
Проблема в том, что если у тебя на входе будет уже отсортированный массив, то он у тебя всё равно будет прогоняться `arr.Length` в степени `arr.Length` итераций.  Можно это количество уменьшить, а каким образом - предлагаю тебе самом подумать.

**Comment by adelsibga** [comment]
Исправил

**Comment by LehaIvanov** [comment]
Адель, сорри, но я не могу такое принять, кажется ты меня не понял. Предыдущая версия даже лучше была. Просто вернись к своему предыдущему коду и ответь на вопрос: "Если массив уже отсортирован, то куда алгоритм не будет заходить, и наоборот - если не отсортирован, то куда алгоритм зайдёт хотя бы один раз?" Соответственно, в том месте тебе нужно поставить переключение флага `isSorted = false`. И с помощью этого флага определять нужно ли тебе продолжать сортировку или нет.

**Comment by LehaIvanov** [comment]
Кстати, я ошибся в твоём алгоритме итераций будет не arr.Length в степени arr.Length, а меньше, но всё равно можно ещё уменьшить.

**Comment by adelsibga** [comment]
Если не отсортирован, то на каждой итерации будет проверять уже отсортированную часть: половина уже отсортирована, половина нет, а значит будет проверять отсортированную половину на условия и просто проходить до конца массива и так пока массив не будет отсортированн
