### ISSUE TITLE
Info: упростить вывод результата

### ISSUE THREAD

**Issue by LehaIvanov** [adelsibga/TL-summer#5]
Я сейчас могу перепутать, но кажется ты можешь выводить строку используя одновременно и `@` и `$` https://stackoverflow.com/a/31638580

То есть как-то так должно получиться:

```
Console.Write($@"Full name: {name},
Age: {age},
Email: {email},
Github link: {github}"
);
```

Но ты проверь, плиз, потому что я не запускал.

**Comment by adelsibga** [comment]
Исправил
