### ISSUE TITLE
Нужно доработать алгоритм

### ISSUE THREAD

**Issue by LehaIvanov** [adelsibga/TL-summer#6]
https://github.com/adelsibga/TL-summer/issues/4#issuecomment-1624206597

**Comment by LehaIvanov** [comment]
И давай раз так пошло, эти изменения через Pull Request cсделаем.

**Comment by adelsibga** [comment]
#7
Где-то накосячил и запорол pull request, в целом все поправил и проверил, что кол-во итераций уменьшилось

**Comment by LehaIvanov** [comment]
Адель, ты сам себе жизнь усложняешь, вот зачем ты функцию создал - ещё и "грязную" - она модифицирает свой входящий параметр.

Совет 1) Избавляйся от лишней функции
Совет 2) Тебе нужно крутить алгоритм до тех пор, пока `swapped == true`, как только `swapped == false`, значит коллекция отсортирована, тут прям напрашивается использовать while. И индекс `i` ты можешь в теле цикла `while` инкрементировать.
Совет 3) Вчера узнал, что можно ещё вот так менять местами значения 

```
(elements[j], elements[j + 1]) = (elements[j + 1], elements[j]);
```

Это называется деструктуризация, и в C# она, оказывается, тоже есть.

**Comment by adelsibga** [comment]
a = a + b - (b = a); В целом, подобная запись, но читаемость ухудшается.
Но запись твоя мне понравилась, удобный свап.

**Comment by adelsibga** [comment]
#10

**Comment by adelsibga** [comment]
Ааааа, понял!

**Comment by adelsibga** [comment]
Доработал алгоритм, понял разницу использования while и for в реализации - на 1 проход меньше если массив отсортирован

**Comment by LehaIvanov** [comment]
Эту лабораторку я у тебя принял.
